---
language: cpp
compiler: gcc
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq curl
#  - sudo apt-get install -y -qq lcov curl
script:
  - curl -sSL https://cmake.org/files/v3.5/cmake-3.5.1-Linux-x86_64.tar.gz | sudo tar -xzC /opt && sudo mv /opt/cmake-3.5.1-Linux-x86_64/bin/* /usr/bin/
  - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && cmake --build . && cmake --build . --target --coveralls

